import Head from 'next/head';
import { FormEvent, useState } from 'react';

import Form from '@/components/Form';
import HeaderLogin from '@/components/HeaderLogin';

import * as S from './styles';

export default function Home() {
  const [value, setValue] = useState<boolean>(false);

  const handleClickEye = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setValue(!value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <HeaderLogin />
        <Form />
      </S.Main>
    </>
  );
}
